Repository snyk/cli, pull requests merged in 2019-07, with the labels that each got.

#677 feat: Behind FF send graphs to new endpoint + tests
  src/cli/commands/monitor.ts
  src/lib/monitor.ts
  src/lib/types.ts
  test/acceptance/cli.acceptance.test.ts
  test/acceptance/fake-server.js
Labels: WIP

#686 feat: Make prepare/prepublish scripts windows compatible
  src/cli/commands/protect/wizard.js
  test/wizard-package-changes.test.ts
Labels: patch, windows

#689 Feat/prune graph
  config.default.json
  src/lib/config.ts
  src/lib/monitor.ts
Labels: 🌳big tree size | large project

#694 feat: out of sync missing deps monitor meta
  src/lib/monitor.ts
  src/lib/types.ts
  test/acceptance/cli.acceptance.test.ts
  test/acceptance/workspaces/npm-out-of-sync-graph/package-lock.json
  test/acceptance/workspaces/npm-out-of-sync-graph/package.json
Labels: npm

#697 feat: update sbt plugin that fixes wrong sbt version retrieving
  package.json
Labels: sbt

#687 feat: use trees for handling sbt projects monitor
  src/lib/monitor.ts
  src/lib/package-managers.ts
  test/acceptance/cli.acceptance.test.ts
  test/acceptance/workspaces/sbt-simple-struts/monitor-graph-result.json
Labels: large projects, sbt, 🌳big tree size | large project
