Repository snyk/cli, pull requests merged in 2019-11, with the labels that each got.

#848 fix: Update interface of DepTree from lockfile
  package.json
  src/lib/monitor.ts
Labels: npm, yarn

#853 Feat/node 6 deprecation warning
  src/cli/index.ts
  src/cli/runtime.ts
  test/acceptance/cli-args.test.ts
  test/acceptance/protect.test.ts
Labels: released

#859 feat: composer dev require
  package.json
  test/acceptance/cli.acceptance.test.ts
  test/acceptance/workspaces/composer-app/composer.json
  test/acceptance/workspaces/composer-app/composer.lock
Labels: boost

#882 fix: bug with --experimental-dep-graph and wrong auth token
  src/cli/commands/monitor/index.ts
  src/lib/errors/authentication-failed-error.ts
  src/lib/errors/index.ts
  src/lib/feature-flags.ts
  test/acceptance/cli-monitor.acceptance.test.ts
Labels: :bug: bug, boost

#884 feat: asynchronously process monitor args
  src/cli/commands/monitor/index.ts
  test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
  test/acceptance/fake-server.ts
Labels: boost
