Repository snyk/cli, pull requests merged in 2019-08, with the labels that each got.

#703 fix: Update ignore policy option description
  help/help.txt
Labels: Documentation

#696 Feat/actionable remediation ui behind ff
  src/cli/commands/test/formatters/legacy-format-issue.ts
  src/cli/commands/test/formatters/remediation-based-format-issues.ts
  src/cli/commands/test/index.ts
  src/lib/snyk-test/legacy.ts
  src/lib/snyk-test/run-test.ts
  test/acceptance/display-test-results.test.ts
  test/acceptance/workspaces/ruby-app/test-graph-response-with-remediation-bad.json
  test/acceptance/workspaces/ruby-app/test-graph-response-with-remediation.json
Labels: requires upstream change

#736 fix: snyk policy command execution error and missed tests
  src/cli/commands/policy.ts
  test/system/cli.test.ts
Labels: boost
