Repository snyk/cli, pull requests merged in 2020-12, with the labels that each got.

#1540 fix: Error output for mismatched options
  src/cli/index.ts
  test/acceptance/cli-args.test.ts
Labels: Cloud Config

#1550 fix: Include all results under a single run
  src/cli/commands/test/iac-output.ts
  src/lib/snyk-test/iac-test-result.ts
  test/acceptance/cli-test/iac/cli-test.iac-dir.spec.ts
  test/acceptance/cli-test/iac/cli-test.iac-utils.ts
Labels: :sun_behind_small_cloud: Cloud Config

#1555 fix: show spinner scanning ecosystem
  src/lib/ecosystems/test.ts
Labels: Tardis

#1557 fix: allow indicative messages for CLI users
  src/lib/errors/non-existing-package-error.ts
  src/lib/snyk-test/run-test.ts
  test/acceptance/cli-test/cli-test.generic.spec.ts
Labels: 🐍 Loki

#1544 fix: add graph conversion while pruning duration analytics
  src/lib/prune.ts
Labels: 🐍 Loki

#1558 feat: Add impact and resolve fields in sarif output.
  src/cli/commands/test/iac-output.ts
  src/lib/snyk-test/iac-test-result.ts
  test/acceptance/cli-test/iac/cli-test.iac-utils.ts
Labels: :sun_behind_small_cloud: Cloud Config

#1570 fix: update go plugin
  package.json
Labels: :bug: bug, go
