Repository snyk/cli, pull requests merged in 2020-08, with the labels that each got.

#1294 chore: update run test exports to modules syntax
  src/lib/snyk-test/index.js
  src/lib/snyk-test/run-test.ts
  test/acceptance/run-test.test.ts
Labels: :skull_and_crossbones: tech services

#1301 fix: propagate failed scans with --all-projects
  .gitignore
  src/cli/commands/monitor/index.ts
  src/cli/commands/test/index.ts
  src/lib/plugins/get-deps-from-plugin.ts
  src/lib/plugins/get-multi-plugin-result.ts
  src/lib/plugins/nodejs-plugin/npm-modules-parser.ts
  src/lib/snyk-test/run-test.ts
  test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
  test/acceptance/cli-test/cli-test.all-projects.spec.ts
Labels: :skull_and_crossbones: tech services

#1312 feat: remove file flag from iac tests
  .github/CODEOWNERS
  src/lib/detect.ts
  src/lib/errors/unsupported-options-iac-error.ts
  src/lib/snyk-test/run-iac-test.ts
  test/acceptance/cli-args.test.ts
  test/acceptance/cli-test/cli-test.iac-k8s.spec.ts
Labels: Cloud Config

#1310 feat: scan gradle projects behind --all-projects
  .gitignore
  src/cli/commands/monitor/formatters/format-monitor-response.ts
  src/cli/commands/monitor/index.ts
  src/cli/commands/test/index.ts
  src/lib/detect.ts
  src/lib/find-files.ts
  src/lib/plugins/get-deps-from-plugin.ts
  test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
  test/acceptance/cli-test/cli-test.acceptance.test.ts
  test/acceptance/cli-test/cli-test.all-projects.spec.ts
  test/acceptance/workspaces/gradle-monorepo/build.gradle
  test/acceptance/workspaces/gradle-monorepo/package-lock.json
  test/acceptance/workspaces/gradle-monorepo/package.json
  test/acceptance/workspaces/gradle-monorepo/settings.gradle
  test/acceptance/workspaces/gradle-monorepo/subproj/.snyk
  test/acceptance/workspaces/gradle-monorepo/subproj/build.gradle
  test/acceptance/workspaces/large-mono-repo/gradle-app/build.gradle
  test/acceptance/workspaces/large-mono-repo/gradle-multi-project/build.gradle
  test/acceptance/workspaces/large-mono-repo/gradle-multi-project/settings.gradle
  test/acceptance/workspaces/large-mono-repo/gradle-multi-project/subproj/.snyk
  test/acceptance/workspaces/large-mono-repo/gradle-multi-project/subproj/build.gradle
  test/find-files.test.ts
  test/fixtures/find-files/gradle-multiple/gradle-another/build.gradle
  test/fixtures/find-files/gradle-multiple/gradle-another/subproject/build.gradle
  test/fixtures/find-files/gradle-multiple/gradle/build.gradle
  test/fixtures/find-files/gradle-multiple/gradle/subproject/build.gradle
Labels: :skull_and_crossbones: tech services

#1309 feat:improve iac test json output
  .github/CODEOWNERS
  src/cli/commands/test/formatters/format-test-meta.ts
  src/cli/commands/test/iac-output.ts
  src/cli/commands/test/index.ts
  src/lib/snyk-test/iac-test-result.ts
  src/lib/snyk-test/legacy.ts
  src/lib/snyk-test/run-iac-test.ts
  src/lib/snyk-test/run-test.ts
  test/acceptance/cli-test/cli-test.iac-k8s.spec.ts
  test/acceptance/cli-test/cli-test.iac-k8s.utils.ts
  test/acceptance/fake-server.ts
  test/acceptance/workspaces/iac-kubernetes/test-iac-high-result.json
  test/acceptance/workspaces/iac-kubernetes/test-iac-medium-result.json
  test/acceptance/workspaces/iac-kubernetes/test-iac-result.json
Labels: Cloud Config

#1328 Feat: enable kotlin gradle all projects
  src/lib/detect.ts
  src/lib/find-files.ts
  test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
  test/acceptance/cli-test/cli-test.all-projects.spec.ts
  test/acceptance/workspaces/kotlin-monorepo/Gemfile
  test/acceptance/workspaces/kotlin-monorepo/Gemfile.lock
  test/acceptance/workspaces/kotlin-monorepo/build.gradle.kts
  test/acceptance/workspaces/kotlin-monorepo/subproj/build.gradle.kts
  test/find-files.test.ts
  test/fixtures/find-files/gradle-and-kotlin/build.gradle
  test/fixtures/find-files/gradle-and-kotlin/build.gradle.kts
  test/fixtures/find-files/gradle-kts/build.gradle.kts
  test/fixtures/find-files/gradle-kts/subproj/build.gradle.kts
Labels: :skull_and_crossbones: tech services

#1344 chore: remove unused gemfile detection
  src/lib/plugins/rubygems/inspectors/gemfile.ts
  src/lib/plugins/rubygems/inspectors/gemspec.ts
  src/lib/plugins/rubygems/inspectors/try-get-spec.ts
Labels: :rocket: Boost, :skull_and_crossbones: tech services

#1348 test: ruby custom gemfile test
  src/lib/plugins/rubygems/inspectors/gemfile.ts
  test/acceptance/cli-test/cli-test.ruby.spec.ts
  test/acceptance/workspaces/ruby-app-custom-names/gemfiles/Gemfile.lock.rails-2.3.6
  test/acceptance/workspaces/ruby-app-custom-names/gemfiles/Gemfile.rails-2.3.6
Labels: :rocket: Boost, :skull_and_crossbones: tech services

#1350 fix: pin transitives for Node 8 support
  package.json
Labels: :rocket: Boost, :skull_and_crossbones: tech services

#1349 chore: introduction of jest test tool
  jest.config.js
  package.json
  test/runtime.spec.ts
  test/runtime.test.ts
Labels: :rocket: Boost

#1325 feat: add snyk-cpp-plugin
  package.json
  src/cli/commands/test/index.ts
  src/cli/modes.ts
  src/lib/ecosystems.ts
  src/lib/types.ts
  test/ecosystems.spec.ts
  test/fixtures/cpp-project/add.cpp
  test/fixtures/cpp-project/add.h
  test/fixtures/cpp-project/display.txt
  test/fixtures/cpp-project/main.cpp
  test/fixtures/cpp-project/scan.json
  test/modes.spec.ts
Labels: :rocket: Boost

#1341 feat: add `-p` as alias for `--prune-repeated-subdependencies`
  help/help.txt
  src/cli/args.ts
  src/cli/commands/monitor/index.ts
  src/lib/snyk-test/run-test.ts
  src/lib/types.ts
  test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
Labels: :construction: WIP, :skull_and_crossbones: tech services

#1329 Fix: handle broken symlinks
  src/cli/args.ts
  src/lib/find-files.ts
  src/lib/snyk-test/run-test.ts
  test/find-files.test.ts
  test/fixtures/find-files/broken-symlink
Labels: :skull_and_crossbones: tech services

#1358 feat: test dependencies for ecosystems
  package.json
  src/cli/commands/test/index.ts
  src/lib/ecosystems.ts
  test/ecosystems.spec.ts
  test/fixtures/cpp-project/display.txt
  test/fixtures/cpp-project/scan.json
  test/fixtures/cpp-project/testResults.json
Labels: :rocket: Boost

#1366 feat: simplify multi scan check with a function
  src/cli/commands/monitor/index.ts
  src/cli/commands/test/index.ts
  src/lib/is-multi-project-scan.ts
  src/lib/options-validator.ts
  src/lib/reachable-vulns.ts
  src/lib/snyk-test/index.js
Labels: :skull_and_crossbones: tech services

#1370 fix: test dependencies scan result type
  src/lib/ecosystems.ts
  src/lib/request/promise.ts
  test/ecosystems.spec.ts
  test/fixtures/cpp-project/display.txt
  test/fixtures/cpp-project/error.txt
  test/fixtures/cpp-project/testResults.json
Labels: :rocket: Boost

#1373 fix: ignore broken files during cpp scan
  package.json
Labels: :rocket: Boost
