Repository snyk/cli, pull requests merged in 2020-09, with the labels that each got.

#1355 feat: Detect and log orphaned or errored gradle project scans by comparing detected files vs scanned.
  .gitignore
  package.json
  src/lib/find-files.ts
  src/lib/plugins/get-deps-from-plugin.ts
  src/lib/plugins/get-extra-project-count.ts
  src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
  test/acceptance/cli-test/cli-test.all-projects.spec.ts
  test/acceptance/workspaces/gradle-with-orphaned-build-file/build.gradle
  test/acceptance/workspaces/gradle-with-orphaned-build-file/orphaned/build.gradle
  test/acceptance/workspaces/gradle-with-orphaned-build-file/settings.gradle
  test/acceptance/workspaces/gradle-with-orphaned-build-file/subproj/build.gradle
  test/find-files.test.ts
Labels: :skull_and_crossbones: tech services

#1383 feat: use snyk-gradle-plugin@3.6.2 that sends back project targetFile
  package.json
  src/lib/plugins/get-deps-from-plugin.ts
  test/acceptance/cli-test/cli-test.all-projects.spec.ts
Labels: ⚠️ DO NOT MERGE ⚠️

#1386 Feat/exit code for no projects
  help/help.txt
  src/cli/index.ts
  src/lib/snyk-test/index.js
  test/acceptance/cli-args.test.ts
  test/fixtures/empty/not-supported.format
  test/smoke/README.md
  test/smoke/alpine/Dockerfile
  test/smoke/spec/snyk_test_spec.sh
  test/system/cli-json-file-output.test.ts
Labels: :skull_and_crossbones: tech services

#1390 feat: improve snyk source test display
  package.json
  src/lib/ecosystems.ts
  test/fixtures/cpp-project/display.txt
  test/fixtures/cpp-project/error.txt
  test/fixtures/cpp-project/testResults.json
Labels: :rocket: Boost

#1424 feat: update scan result test dependencies
  package.json
  src/lib/ecosystems.ts
  test/ecosystems.spec.ts
Labels: :rocket: Boost

#1422 feat: add reachable vulnerabilities support for gradle
  package.json
  src/lib/monitor/index.ts
  src/lib/package-managers.ts
  test/acceptance/cli-reachable-vulns.test.ts
  test/acceptance/cli-test/cli-test.gradle.spec.ts
  test/reachable-vulns.test.ts
Labels: ⚠️ DO NOT MERGE ⚠️
