Repository snyk/cli, pull requests merged in 2020-03, with the labels that each got.

#1035 fix: improved python --command documentation
  help/help.txt
Labels: boost

#1037 Refactor/snyk cli tests from js to ts
  test/prompts-no-remediation.test.js
  test/prompts-no-remediation.test.ts
  test/protect-patch-order.test.js
  test/protect-patch-order.test.ts
  test/updater.test.ts
  test/user-config.test.ts
Labels: ⚠️ DO NOT MERGE ⚠️

#1056 docs: fix up some of the language
  help/help.txt
Labels: Documentation
