Repository snyk/cli, pull requests merged in 2020-06, with the labels that each got.

#1162 chore: add hammer team as codeowners on CLI
  .github/CODEOWNERS
Labels: :hammer: hammer, :rocket: Boost

#1176 fix: prune depGraph paths accuracy
  config.default.json
  src/lib/config.ts
  src/lib/monitor/index.ts
  src/lib/prune.ts
  src/lib/snyk-test/run-test.ts
Labels: :rocket: Boost

#1181 feat: allow large projects to pass after prune
  config.default.json
Labels: :rocket: Boost

#1165 feat/support depgraph deptree coexistence from plugins
  package.json
  src/cli/commands/monitor/index.ts
  src/lib/monitor/index.ts
  src/lib/package-managers.ts
  src/lib/plugins/convert-single-splugin-res-to-multi-custom.ts
  src/lib/plugins/get-deps-from-plugin.ts
  src/lib/plugins/get-multi-plugin-result.ts
  src/lib/print-deps.ts
  src/lib/project-metadata/index.ts
  src/lib/project-metadata/target-builders/container.ts
  src/lib/project-metadata/target-builders/git.ts
  src/lib/prune.ts
  src/lib/snyk-test/run-test.ts
  src/lib/utils.ts
  test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
  test/get-remote-url.test.ts
Labels: :rocket: Boost

#1214 feat: gradle support of depgraph
  package.json
Labels: :rocket: Boost

#1215 feat: expose snyk-test debug context
  src/cli/args.ts
Labels: :skull_and_crossbones: tech services

#1221 chore: type scanned projects to graph or tree
  src/lib/snyk-test/run-test.ts
Labels: :rocket: Boost

#1222 fix: allows scanning even if a single proj import fails
  src/cli/commands/monitor/index.ts
Labels: :rocket: Boost

#1223 feat: unify policy handling & plucking
  src/cli/commands/monitor/index.ts
  src/cli/commands/protect/index.ts
  src/cli/commands/protect/wizard.ts
  src/lib/monitor/index.ts
  src/lib/plugins/nodejs-plugin/npm-modules-parser.ts
  src/lib/policy/find-and-load-policy.ts
  src/lib/policy/index.ts
  src/lib/policy/pluck-policies.ts
  src/lib/snyk-test/run-test.ts
  src/lib/types.ts
  test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
Labels: :skull_and_crossbones: tech services

#1230 refactor: drop unused gradle from experimental
  src/lib/package-managers.ts
Labels: :rocket: Boost

#1229 feat: update snyk test prune logic
  src/lib/prune.ts
  src/lib/snyk-test/run-test.ts
Labels: :rocket: Boost

#1224 fix: policies to be correctly picked up from nested scans
  src/lib/monitor/index.ts
  src/lib/policy/find-and-load-policy.ts
  src/lib/snyk-test/run-test.ts
  test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
  test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
  test/acceptance/cli-test/cli-test.all-projects.spec.ts
  test/acceptance/cli-test/cli-test.gradle.spec.ts
  test/acceptance/cli-test/cli-test.yarn.spec.ts
  test/acceptance/workspaces/gradle-multi-project/build.gradle
  test/acceptance/workspaces/gradle-multi-project/settings.gradle
  test/acceptance/workspaces/gradle-multi-project/subproj/.snyk
  test/acceptance/workspaces/gradle-multi-project/subproj/build.gradle
  test/acceptance/workspaces/mono-repo-with-ignores/package-lock.json
  test/acceptance/workspaces/mono-repo-with-ignores/package.json
  test/acceptance/workspaces/mono-repo-with-ignores/vulnerable/.snyk
  test/acceptance/workspaces/mono-repo-with-ignores/vulnerable/package-lock.json
  test/acceptance/workspaces/mono-repo-with-ignores/vulnerable/package.json
  test/acceptance/workspaces/yarn-package/.snyk
  test/package-no-name.test.ts
Labels: :skull_and_crossbones: tech services

#1246 fix: break of cyclic dependencies on gradle cli
  package.json
Labels: :rocket: Boost

#1183 feat: introduce yarn workspace scanning test & monitor only
  help/help.txt
  src/cli/args.ts
  src/cli/commands/monitor/formatters/format-monitor-response.ts
  src/cli/commands/monitor/index.ts
  src/cli/index.ts
  src/lib/errors/exclude-flag-invalid-input.ts
  src/lib/errors/option-missing-error.ts
  src/lib/options-validator.ts
  src/lib/plugins/get-deps-from-plugin.ts
  src/lib/plugins/nodejs-plugin/yarn-workspaces-parser.ts
  src/lib/reachable-vulns.ts
  src/lib/snyk-test/index.js
  src/lib/snyk-test/run-test.ts
  src/lib/types.ts
  test/acceptance/cli-args.test.ts
  test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
  test/acceptance/cli-test/cli-test.acceptance.test.ts
  test/acceptance/cli-test/cli-test.yarn-workspaces.spec.ts
  test/acceptance/workspaces/package.json
  test/acceptance/workspaces/yarn-workspace-out-of-sync/package.json
  test/acceptance/workspaces/yarn-workspace-out-of-sync/packages/apples/package.json
  test/acceptance/workspaces/yarn-workspace-out-of-sync/packages/tomatoes/package.json
  test/acceptance/workspaces/yarn-workspace-out-of-sync/yarn.lock
  test/acceptance/workspaces/yarn-workspaces/.snyk
  test/acceptance/workspaces/yarn-workspaces/package.json
  test/acceptance/workspaces/yarn-workspaces/packages/apples/.snyk
  test/acceptance/workspaces/yarn-workspaces/packages/apples/package.json
  test/acceptance/workspaces/yarn-workspaces/packages/tomatoes/package.json
  test/acceptance/workspaces/yarn-workspaces/yarn.lock
Labels: :skull_and_crossbones: tech services

#1247 fix: allow IPv6 if supported
  package.json
  src/cli/commands/auth/index.ts
  test/system/auth.test.ts
Labels: :rocket: Boost, ⚠️ DO NOT MERGE ⚠️
