Repository snyk/cli, pull requests merged in 2020-11, with the labels that each got.

#1497 Feat/add poetry support
  package.json
  src/lib/detect.ts
  src/lib/find-files.ts
  src/lib/package-managers.ts
  src/lib/plugins/index.ts
  test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
  test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
  test/acceptance/cli-test/cli-test.all-projects.spec.ts
  test/acceptance/cli-test/cli-test.python.spec.ts
  test/acceptance/workspaces/mono-repo-poetry/package-lock.json
  test/acceptance/workspaces/mono-repo-poetry/package.json
  test/acceptance/workspaces/mono-repo-poetry/python/poetry.lock
  test/acceptance/workspaces/mono-repo-poetry/python/pyproject.toml
  test/acceptance/workspaces/poetry-app/poetry.lock
  test/acceptance/workspaces/poetry-app/pyproject.toml
Labels: Tardis

#1520 feat: monitor cpp projects
  package.json
  src/cli/modes.ts
  src/lib/ecosystems/plugins.ts
  src/lib/plugins/get-extra-project-count.ts
  test/all-projects-from-plugins.spec.ts
  test/ecosystems-monitor-cpp.spec.ts
  test/ecosystems-test-cpp.spec.ts
  test/ecosystems.spec.ts
  test/fixtures/cpp-project/monitor-dependencies-response.json
  test/modes.spec.ts
Labels: Tardis, ⚠️ DO NOT MERGE ⚠️

#1523 fix: restore analytics for tracking Docker/container calls
  src/lib/snyk-test/run-test.ts
Labels: ⚠️ DO NOT MERGE ⚠️

#1529 fix: snyk-cpp-plugin blocking event loop
  package.json
Labels: Tardis

#1548 fix: gradle deps resolution conflicts
  package.json
  test/fixtures/gradle-prune-repeated-deps/gradle-pruned-dep-graph.json
Labels: Tardis
