Repository snyk/cli, pull requests merged in 2020-10, with the labels that each got.

#1443 refactor: circle-ci jvm unix using sdkman install
  .circleci/config.yml
Labels: :rocket: Boost

#1442 fix: missing prune cmd on snyk monitor
  src/lib/monitor/index.ts
  test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
  test/fixtures/gradle-prune-repeated-deps/build.gradle
  test/fixtures/gradle-prune-repeated-deps/gradle-pruned-dep-graph.json
Labels: :rocket: Boost

#1448 fix: correct match check for package.json when not part of a workspace
  src/cli/args.ts
  src/lib/plugins/get-deps-from-plugin.ts
  src/lib/plugins/nodejs-plugin/yarn-workspaces-parser.ts
  test/acceptance/cli-test/cli-test.all-projects.spec.ts
  test/acceptance/cli-test/cli-test.yarn-workspaces.spec.ts
  test/acceptance/workspaces/yarn-workspaces/not-part-of-workspace/package.json
Labels: :skull_and_crossbones: tech services

#1452 feat: release latest snyk-gradle-plugin with extra logging
  package.json
Labels: :skull_and_crossbones: tech services

#1489 fix: enhance gradle cycles detection
  package.json
  test/fixtures/gradle-prune-repeated-deps/gradle-pruned-dep-graph.json
Labels: Tardis
