Repository snyk/cli, pull requests merged in 2020-05, with the labels that each got.

#1100 fix: docker error on monitoring multiple projects
  docker/docker-entrypoint.sh
Labels: :whale: docker

#1103 chore: bump @snyk/dep-graph to 1.18.3
  package.json
Labels: boost

#1111 chore: forgotten log removed to reduce noise
  test/cli-server.js
Labels: boost

#1113 fix: updated test command so Circle will test properly
  .circleci/config.yml
Labels: boost

#1116 feat: add IPv6 detection to fix auth bug
  package.json
  src/cli/commands/auth/index.ts
  src/lib/request/request.ts
  src/lib/request/types.ts
  test/system/cli.test.ts
Labels: :rose: enhancement

#1148 fix: initial graph support to solve gradle oom
  package.json
Labels: :rocket: Boost

#1150 fix: go-plugin js heap oom using reverse for loop
  package.json
Labels: :rocket: Boost, go

#1156 feat: support gradle v2 on new task and drop legacy one
  package.json
Labels: :rocket: Boost
