Repository snyk/cli, pull requests merged in 2020-07, with the labels that each got.

#1255 feat: increases max limit of a project paths to be processed
  config.default.json
Labels: :rocket: Boost

#1245 feat: bump default depth to 4
  help/help.txt
  src/lib/find-files.ts
  test/find-files.test.ts
Labels: :skull_and_crossbones: tech services

#1233 feat: detect other files & suggest to use --all-projects
  src/cli/commands/monitor/formatters/format-monitor-response.ts
  src/cli/commands/monitor/index.ts
  src/cli/commands/test/index.ts
  src/lib/plugins/get-extra-project-count.ts
  src/lib/plugins/get-sub-project-count.ts
  src/lib/snyk-test/run-test.ts
  test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
  test/acceptance/cli-test/cli-test.ruby.spec.ts
Labels: :skull_and_crossbones: tech services, ⚠️ DO NOT MERGE ⚠️

#1254 feat: bump nodejs-lockfile-parser
  package.json
  src/lib/spinner.ts
  tsconfig.json
Labels: :rocket: Boost

#1234 feat: add support yarn v2
  package.json
  src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
  test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
  test/acceptance/cli-test/cli-test.yarn.spec.ts
  test/acceptance/workspaces/yarn-v2/package.json
  test/acceptance/workspaces/yarn-v2/yarn.lock
Labels: :rocket: Boost

#1271 feat: if matched display the project ID
  src/lib/snyk-test/legacy.ts
Labels: :skull_and_crossbones: tech services

#1277 feat: add gomodules support depgraph, drop deptree
  package.json
Labels: :rocket: Boost

#1293 fix: correct infrastructure as code error import
  src/lib/snyk-test/index.js
  test/acceptance/cli-args.test.ts
  test/acceptance/workspaces/helmconfig/Chart.yaml
Labels: :skull_and_crossbones: tech services

#1292 chore: simplify supported projects validation on test
  src/lib/snyk-test/index.js
Labels: :skull_and_crossbones: tech services
