Repository snyk/cli, pull requests merged in 2021-03, with the labels that each got.

#1666 chore: bump flaky cpp test timeout
  test/ecosystems-test-cpp.spec.ts
Labels: 🐂 Team Bull

#1659 feat: initial snyk-fix package setup & loadPlugin functionality
  .github/CODEOWNERS
  .gitignore
  packages/snyk-fix/README.md
  packages/snyk-fix/SECURITY.md
  packages/snyk-fix/jest.config.js
  packages/snyk-fix/package.json
  packages/snyk-fix/src/index.ts
  packages/snyk-fix/src/lib/errors/custom-error.ts
  packages/snyk-fix/src/lib/errors/error-to-user-message.ts
  packages/snyk-fix/src/lib/errors/unsupported-type-error.ts
  packages/snyk-fix/src/plugins/load-plugin.ts
  packages/snyk-fix/src/plugins/python/index.ts
  packages/snyk-fix/src/plugins/types.ts
  packages/snyk-fix/src/types.ts
  packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
  packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
  packages/snyk-fix/test/unit/fix.spec.ts
  packages/snyk-fix/tsconfig.json
  release-scripts/update-versions.sh
  tsconfig.json
Labels: 🐂 Team Bull

#1674 test: iac local exec new unit tests - part 1
  .github/CODEOWNERS
  jest.config.js
  package.json
  test/iac-unit-tests/file-loader.fixtures.ts
  test/iac-unit-tests/file-loader.spec.ts
  test/iac-unit-tests/file-parser.fixtures.ts
  test/iac-unit-tests/file-parser.spec.ts
  test/iac-unit-tests/file-scanner.fixtures.ts
  test/iac-unit-tests/file-scanner.spec.ts
Labels: :sun_behind_small_cloud: Cloud Config

#1684 Feat/snyk fix requirements txt support v1
  packages/snyk-fix/jest.config.js
  packages/snyk-fix/package.json
  packages/snyk-fix/src/index.ts
  packages/snyk-fix/src/lib/errors/custom-error.ts
  packages/snyk-fix/src/lib/errors/error-to-user-message.ts
  packages/snyk-fix/src/lib/errors/missing-file-name.ts
  packages/snyk-fix/src/lib/errors/missing-remediation-data.ts
  packages/snyk-fix/src/lib/errors/no-fixes-applied.ts
  packages/snyk-fix/src/lib/output-formatters/format-successful-item.ts
  packages/snyk-fix/src/lib/output-formatters/format-unresolved-item.ts
  packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
  packages/snyk-fix/src/plugins/load-plugin.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements.ts
  packages/snyk-fix/src/plugins/python/handlers/update-dependencies/index.ts
  packages/snyk-fix/src/plugins/python/handlers/update-dependencies/requirements-file-parser.ts
  packages/snyk-fix/src/plugins/python/index.ts
  packages/snyk-fix/src/plugins/python/load-handler.ts
  packages/snyk-fix/src/plugins/python/supported-project-types.ts
  packages/snyk-fix/src/plugins/types.ts
  packages/snyk-fix/src/types.ts
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/__snapshots__/update-dependencies.spec.ts.snap
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/update-dependencies.spec.ts
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/basic-with-newline/prod.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/basic/prod.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/long-versions/prod.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/lower-case-dep/req.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/monorepo/with-comparator/prod.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/pip-app-multiple-versions/base.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/pip-app-multiple-versions/base2.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/pip-app-multiple-versions/core/requirements.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/pip-app-multiple-versions/lib/requirements.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/pip-app-multiple-versions/requirements.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/pip-app/base.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/pip-app/base2.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/pip-app/core/requirements.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/pip-app/lib/requirements.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/pip-app/requirements.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/python-markers/prod.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-comparator/prod.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-custom-formatting/requirements.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-require/dev.txt
  packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
  packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
  packages/snyk-fix/test/unit/fix.spec.ts
  packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/format-successful-item.spec.ts.snap
  packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/format-unresolved-item.spec.ts.snap
  packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/show-results-summary.spec.ts.snap
  packages/snyk-fix/test/unit/lib/output-formatters/format-successful-item.spec.ts
  packages/snyk-fix/test/unit/lib/output-formatters/format-unresolved-item.spec.ts
  packages/snyk-fix/test/unit/lib/output-formatters/show-results-summary.spec.ts
  packages/snyk-fix/test/unit/plugins/python/__snapshots__/pip-requirements.spec.ts.snap
  packages/snyk-fix/test/unit/plugins/python/handlers/index.spec.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/update-dependencies/__snapshots__/update-dependencies.spec.ts.snap
  packages/snyk-fix/test/unit/plugins/python/handlers/update-dependencies/update-dependencies.spec.ts
  packages/snyk-fix/test/unit/plugins/python/pip-requirements.spec.ts
  packages/snyk-fix/test/unit/plugins/python/workspaces/pip-app-with-python-markers/requirements.txt
  packages/snyk-fix/test/unit/plugins/python/workspaces/pip-app/requirements.txt
Labels: 🐂 Team Bull

#1687 refactor: validateCredentials token check
  src/cli/commands/test/index.ts
  src/cli/commands/test/validate-credentials.ts
Labels: :construction: WIP, 🐂 Team Bull

#1688 refactor: generate snyk test error
  src/cli/commands/test/generate-snyk-test-error.ts
  src/cli/commands/test/index.ts
Labels: 🐂 Team Bull

#1667 Test/use mock server
  test/cli-json-file-output.spec.ts
Labels: 🐂 Team Bull

#1697 feat: extract validate test options
  src/cli/commands/test/index.ts
  src/cli/commands/test/validate-test-options.ts
Labels: 🐂 Team Bull

#1698 feat: convert args into paths & options
  src/cli/commands/monitor/index.ts
  src/cli/commands/process-command-args.ts
  src/cli/commands/test/index.ts
  test/process-command-args.spec.ts
Labels: 🐂 Team Bull

#1690 [IaC] feat: fetch policy bundle from S3 for local scans [Beta]- CC-627
  .circleci/config.yml
  jest.config.js
  package.json
  src/cli/commands/test/iac-local-execution/file-utils.ts
  src/cli/commands/test/iac-local-execution/index.ts
  src/cli/commands/test/iac-local-execution/local-cache.ts
  test/iac-unit-tests/file-utils.spec.ts
  test/iac-unit-tests/local-cache.spec.ts
Labels: :sun_behind_small_cloud: Cloud Config

#1709 refactor: Remove writeable stream to stop writing tarball to the disk [IaC]
  src/cli/commands/test/iac-local-execution/file-utils.ts
  src/cli/commands/test/iac-local-execution/local-cache.ts
  test/iac-unit-tests/file-utils.spec.ts
  test/iac-unit-tests/local-cache.spec.ts
Labels: :sun_behind_small_cloud: Cloud Config

#1704 refactor: set default test options
  src/cli/commands/protect/index.ts
  src/cli/commands/protect/wizard.ts
  src/cli/commands/test/index.ts
  src/cli/commands/test/set-default-test-options.ts
  src/lib/types.ts
  test/run-test.spec.ts
  test/set-default-test-options.spec.ts
  test/snyk-code-test.spec.ts
Labels: 🐂 Team Bull

#1716 feat: return fix summary & meta
  packages/snyk-fix/src/index.ts
  packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
  packages/snyk-fix/src/plugins/python/index.ts
  packages/snyk-fix/src/types.ts
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/update-dependencies.spec.ts
  packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
  packages/snyk-fix/test/unit/fix.spec.ts
Labels: 🐂 Team Bull

#1729 feat: fallback to type when missing targetFile
  packages/snyk-fix/src/lib/output-formatters/format-unresolved-item.ts
  packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/format-unresolved-item.spec.ts.snap
  packages/snyk-fix/test/unit/lib/output-formatters/format-unresolved-item.spec.ts
Labels: 🐂 Team Bull

#1726 fix: Error messages when Terraform validation fails due to bad credentials
  src/lib/iac/iac-parser.ts
  src/lib/request/index.ts
Labels: :sun_behind_small_cloud: Cloud Config

#1733 feat: let CLI display the full summary
  packages/snyk-fix/src/index.ts
Labels: 🐂 Team Bull

#1725 feat: Add iac metadata for analytics [CC-731]
  src/cli/commands/test/iac-local-execution/analytics.ts
  src/cli/commands/test/iac-local-execution/file-parser.ts
  src/cli/commands/test/iac-local-execution/index.ts
Labels: :sun_behind_small_cloud: Cloud Config

#1738 @snyk/fix: Extract requirements.txt version provenance (-r, -c directives)
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/extract-version-provenance.ts
  packages/snyk-fix/src/types.ts
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/extract-provenance.spec.ts
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-multiple-requires/base.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-multiple-requires/dev.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-multiple-requires/reqs/base.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-multiple-requires/reqs/constraints.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-recursive-requires/base.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-recursive-requires/constraints.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-recursive-requires/dev.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-require-folder-up/base.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-require-folder-up/reqs/requirements.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/with-require/base.txt
Labels: 🐂 Team Bull

#1748 feat: Update iac --help documentation to include experimental flag
  help/commands-docs/_EXAMPLES.md
  help/commands-docs/iac-examples.md
  help/commands-docs/iac.md
  test/args.test.ts
Labels: :sun_behind_small_cloud: Cloud Config

#1755 feat(@snyk/fix): unify calculating relevant pins & upgrades
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/calculate-relevant-fixes.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/generate-pins.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/generate-upgrades.ts
  packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
Labels: 🐂 Team Bull

#1757 Feat/improve parse requirements
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/extract-version-provenance.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/index.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/requirements-file-parser.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/update-dependencies/apply-upgrades.spec.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/update-dependencies/generate-pins.spec.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/update-dependencies/generate-upgrades.spec.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/update-dependencies/update-dependencies.spec.ts
Labels: 🐂 Team Bull

#1765 refactor: Fixes iac smoke tests to be less explicit
  test/smoke/spec/iac/snyk_test_directory_spec.sh
  test/smoke/spec/iac/snyk_test_k8s_spec.sh
  test/smoke/spec/iac/snyk_test_local_exec_spec.sh
  test/smoke/spec/iac/snyk_test_terraform_spec.sh
Labels: --fix, :sun_behind_small_cloud: Cloud Config

#1770 Fix: target different Node versions for binaries for pkg-fetch
  release-scripts/make-binaries.sh
Labels: --fix

#1758 refactor: remove SNYK_IAC_SKIP_BUNDLE_DOWNLOAD env var from code
  src/cli/commands/test/iac-local-execution/local-cache.ts
  test/jest/unit/iac-unit-tests/local-cache.spec.ts
  test/smoke/spec/iac/snyk_test_local_exec_spec.sh
Labels: :sun_behind_small_cloud: Cloud Config

#1768 refactor: Remove unused env var from circleci config
  .circleci/config.yml
Labels: :sun_behind_small_cloud: Cloud Config

#1762 feat: Delete local .iac-data directory after scan is finished [CC-765]
  package.json
  src/cli/commands/test/iac-local-execution/index.ts
  src/cli/commands/test/iac-local-execution/local-cache.ts
  test/jest/unit/iac-unit-tests/local-cache.spec.ts
Labels: :sun_behind_small_cloud: Cloud Config

#1772 refactor: remove if guard that checks if dir exists
  src/cli/commands/test/iac-local-execution/local-cache.ts
  test/jest/unit/iac-unit-tests/local-cache.spec.ts
Labels: :sun_behind_small_cloud: Cloud Config

#1775 feat: use break cycles logic of depgraph for snyk-gradle
  package.json
  test/fixtures/gradle-prune-repeated-deps/gradle-pruned-dep-graph.json
Labels: Tardis

#1777 Feat: v1 fix with version provenance for requirements.txt projects
  packages/snyk-fix/src/lib/errors/invalid-workspace.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/extract-version-provenance.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/is-supported.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/generate-pins.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/generate-upgrades.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/index.ts
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/__snapshots__/update-dependencies.spec.ts.snap
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/update-dependencies.spec.ts
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/app-with-already-fixed/base.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/app-with-already-fixed/core/requirements.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/app-with-already-fixed/lib/requirements.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/app-with-already-fixed/requirements.txt
  packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/pip-app/requirements.txt
  packages/snyk-fix/test/unit/fix.spec.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/update-dependencies/update-dependencies.spec.ts
  packages/snyk-fix/test/unit/plugins/python/is-supported.spec.ts
Labels: 🐂 Team Bull

#1707 Feat: snyk fix v1 (Python) in behind FF
  .circleci/config.yml
  package.json
  src/cli/commands/fix/convert-legacy-test-result-to-new.ts
  src/cli/commands/fix/convert-legacy-test-result-to-scan-result.ts
  src/cli/commands/fix/convert-legacy-tests-results-to-fix-entities.ts
  src/cli/commands/fix/get-display-path.ts
  src/cli/commands/fix/index.ts
  src/cli/commands/fix/validate-fix-command-is-supported.ts
  src/cli/commands/index.js
  src/cli/commands/test/format-test-error.ts
  src/cli/commands/test/index.ts
  src/cli/commands/test/set-default-test-options.ts
  src/lib/ecosystems/types.ts
  src/lib/errors/command-not-supported.ts
  src/lib/errors/not-supported-by-ecosystem.ts
  src/lib/plugins/get-deps-from-plugin.ts
  src/lib/snyk-test/assemble-payloads.ts
  src/lib/snyk-test/run-test.ts
  src/lib/types.ts
  test/acceptance/fixtures/pip-app-with-remediation/test-graph-results.json
  test/acceptance/workspaces/pip-app-custom/base.txt
  test/cli-fix.functional.spec.ts
  test/cli-fix.system.spec.ts
  test/fixtures/snyk-fix/test-result-pip-with-remediation.json
  test/get-display-path.functional.spec.ts
  test/lib/__snapshots__/convert-legacy-test-result-to-new.spec.ts.snap
  test/lib/__snapshots__/convert-legacy-test-result-to-scan-result.spec.ts.snap
  test/lib/__snapshots__/convert-legacy-tests-results-to-fix-entities.spec.ts.snap
  test/lib/convert-legacy-test-result-to-new.spec.ts
  test/lib/convert-legacy-test-result-to-scan-result.spec.ts
  test/lib/convert-legacy-tests-results-to-fix-entities.spec.ts
  test/smoke/spec/snyk_fix_spec.sh
  test/validate-fix-command-is-supported.spec.ts
Labels: 🐂 Team Bull

#1784 feat: @snyk/fix supports -r directive
  package.json
Labels: 🐂 Team Bull

#1780 chore: Add error types and debug logs for IaC [CC-754, CC-764]
  src/cli/commands/test/iac-local-execution/file-loader.ts
  src/cli/commands/test/iac-local-execution/file-parser.ts
  src/cli/commands/test/iac-local-execution/file-scanner.ts
  src/cli/commands/test/iac-local-execution/file-utils.ts
  src/cli/commands/test/iac-local-execution/local-cache.ts
  src/cli/commands/test/iac-local-execution/parsers/kubernetes-parser.ts
  src/cli/commands/test/iac-local-execution/parsers/terraform-file-parser.ts
  src/cli/commands/test/iac-local-execution/parsers/terraform-plan-parser.ts
  src/cli/commands/test/iac-local-execution/results-formatter.ts
  src/cli/commands/test/iac-local-execution/types.ts
  test/jest/unit/iac-unit-tests/file-loader.spec.ts
  test/jest/unit/iac-unit-tests/file-parser.fixtures.ts
  test/jest/unit/iac-unit-tests/file-parser.spec.ts
  test/jest/unit/iac-unit-tests/file-scanner.spec.ts
  test/jest/unit/iac-unit-tests/local-cache.spec.ts
  test/jest/unit/iac-unit-tests/terraform-plan-parser.fixtures.ts
  test/jest/unit/iac-unit-tests/terraform-plan-parser.spec.ts
  test/smoke/spec/iac/snyk_test_local_exec_spec.sh
Labels: :sun_behind_small_cloud: Cloud Config
