Repository snyk/cli, pull requests merged in 2021-06, with the labels that each got.

#1985 feat: use latest pipfile fix package
  packages/snyk-fix/package.json
  packages/snyk-fix/src/index.ts
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
Labels: 🐂 Team Bull

#2015 fix: use classifier in maven package name
  package.json
Labels: Tardis

#2017 test: re-use the entity generator helpers across all tests
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pip-requirements/update-dependencies/update-dependencies.spec.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/update-dependencies.spec.ts
  packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
  packages/snyk-fix/test/helpers/read-file-helper.ts
Labels: 🐂 Team Bull

#2016 Fix: partition Python projects by fixable earlier on in Snyk fix flow
  packages/snyk-fix/package.json
  packages/snyk-fix/src/lib/errors/custom-error.ts
  packages/snyk-fix/src/lib/errors/invalid-workspace.ts
  packages/snyk-fix/src/lib/errors/missing-remediation-data.ts
  packages/snyk-fix/src/lib/errors/no-fixes-applied.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
  packages/snyk-fix/src/plugins/python/index.ts
Labels: 🐂 Team Bull

#2020 chore: drop unused Pipfile check
  packages/snyk-fix/src/plugins/python/get-handler-type.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/pip-requirements/get-handler-type.spec.ts
Labels: 🐂 Team Bull

#2022 feat(@snyk/fix): make tool version check generic
  packages/snyk-fix/src/plugins/package-tool-supported.ts
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/index.ts
  packages/snyk-fix/test/acceptance/plugins/package-tool-supported.spec.ts
Labels: 🐂 Team Bull

#2024 test(@snyk/fix): assert expected fix parameters sent
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/update-dependencies.spec.ts
Labels: 🐂 Team Bull

#2028 chore: allow @ts-ignore comments in test only
  .eslintrc.json
Labels: 🐂 Team Bull

#2027 chore: make standardizePackageName() shared in Python plugin
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/calculate-relevant-fixes.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/generate-pins.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/generate-upgrades.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/requirements-file-parser.ts
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
  packages/snyk-fix/src/plugins/python/standardize-package-name.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/pip-requirements/update-dependencies/standardize-package-name.spec.ts
Labels: 🐂 Team Bull

#2032 refactor/remove iac policyEngineType metadata
  src/cli/commands/test/iac-local-execution/types.ts
  test/jest/unit/iac-unit-tests/file-scanner.fixtures.ts
  test/jest/unit/iac-unit-tests/results-formatter.fixtures.ts
  test/smoke/.iac-data/k8s_data.json
  test/smoke/.iac-data/tf_data.json
Labels: :sun_behind_small_cloud: Cloud Config

#2029 Feat: Poetry support for @snyk/fix
  packages/snyk-fix/package.json
  packages/snyk-fix/src/plugins/load-plugin.ts
  packages/snyk-fix/src/plugins/package-tool-supported.ts
  packages/snyk-fix/src/plugins/python/get-handler-type.ts
  packages/snyk-fix/src/plugins/python/handlers/poetry/index.ts
  packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
  packages/snyk-fix/src/plugins/python/load-handler.ts
  packages/snyk-fix/src/plugins/python/map-entities-per-handler-type.ts
  packages/snyk-fix/src/plugins/python/supported-handler-types.ts
  packages/snyk-fix/src/types.ts
  packages/snyk-fix/test/acceptance/plugins/package-tool-supported.spec.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/update-dependencies.spec.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/fails-to-lock/poetry.lock
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/fails-to-lock/pyproject.toml
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/non-existent/poetry.lock
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/non-existent/pyproject.toml
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/simple/poetry.lock
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/simple/pyproject.toml
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/with-dev-deps/poetry.lock
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/with-dev-deps/pyproject.toml
  packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
  packages/snyk-fix/test/unit/fix.spec.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/pip-requirements/get-handler-type.spec.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/pip-requirements/map-entities-per-handler-type.spec.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/poetry/generate-upgrades.spec.ts
  packages/snyk-fix/test/unit/plugins/python/is-supported.spec.ts
Labels: 🐂 Team Bull

#2035 feat: support --command for Poetry fix
  packages/snyk-fix/package.json
  packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/update-dependencies.spec.ts
Labels: 🐂 Team Bull

#2033 feat: release @snyk/fix Poetry support
  package.json
Labels: 🐂 Team Bull

#2047 fix(@snyk/fix): drop prod prettier from fix packages
  packages/snyk-fix/package.json
Labels: 🐂 Team Bull

#2050 fix: drop prettier as prod dep from @snyk/fix
  package.json
Labels: 🐂 Team Bull

#2043 Feat: snyk fix output improvement
  packages/snyk-fix/src/index.ts
  packages/snyk-fix/src/lib/errors/common.ts
  packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
  packages/snyk-fix/src/plugins/python/index.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pip-requirements/update-dependencies/__snapshots__/update-dependencies.spec.ts.snap
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/update-dependencies.spec.ts
  packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
  packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/show-results-summary.spec.ts.snap
  packages/snyk-fix/test/unit/lib/output-formatters/show-results-summary.spec.ts
Labels: 🐂 Team Bull

#2058 docs: adds details for critical severity usage
  help/README.md
  help/commands-docs/_SNYK_COMMAND_OPTIONS.md
  help/commands-docs/container.md
Labels: 🌔 Apollo

#2059 feat: filter out non-vulnerable from summary
  packages/snyk-fix/src/index.ts
  packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
  packages/snyk-fix/src/partition-by-vulnerable.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pip-requirements/update-dependencies/__snapshots__/update-dependencies.spec.ts.snap
  packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
  packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
  packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/show-results-summary.spec.ts.snap
  packages/snyk-fix/test/unit/lib/output-formatters/format-unresolved-item.spec.ts
  packages/snyk-fix/test/unit/lib/output-formatters/show-results-summary.spec.ts
  test/jest/unit/lib/commands/fix/fix.spec.ts
Labels: 🐂 Team Bull

#2062 feat: release @snyk/fix with improved output
  package.json
Labels: 🐂 Team Bull

#2063 feat: send back meta on fixed, failed & total issues
  packages/snyk-fix/src/index.ts
  packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
  packages/snyk-fix/src/types.ts
  packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
Labels: 🐂 Team Bull

#2065 feat: send `snyk fix` specific analytics
  package.json
  src/cli/commands/fix/index.ts
  test/acceptance/workspaces/monorepo-with-nuget/src/cartservice-nuget/obj/Debug/netcoreapp1.1/cartservice.csproj.AssemblyReference.cache
  test/jest/unit/lib/commands/fix/fix.spec.ts
Labels: 🐂 Team Bull
