Repository snyk/cli, pull requests merged in 2021-05, with the labels that each got.

#1874 fix: gradle scanning error due of mishandled root value
  package.json
Labels: Gradle, Tardis

#1855 feat(@snyk/fix): propagate cli test options
  packages/snyk-fix/src/types.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pip-requirements/update-dependencies/update-dependencies.spec.ts
  packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
  packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
  src/lib/types.ts
Labels: 🐂 Team Bull

#1886 feat: exit code 0 if nothing is vulnerable
  src/cli/commands/fix/index.ts
  test/fixtures/snyk-fix/test-result-pip-no-vulns.json
  test/jest/unit/lib/commands/fix/fix.spec.ts
Labels: 🐂 Team Bull

#1881 refactor: iac documentation url in outputs
  src/cli/commands/test/iac-local-execution/results-formatter.ts
  src/cli/commands/test/iac-output.ts
  src/lib/snyk-test/iac-test-result.ts
  test/acceptance/cli-test/iac/cli-test.iac-utils.ts
  test/jest/unit/iac-unit-tests/results-formatter.fixtures.ts
Labels: :sun_behind_small_cloud: Cloud Config

#1906 fix: gradle project name being empty string
  package.json
Labels: Tardis

#1922 Fix: total issue count
  packages/snyk-fix/src/index.ts
  packages/snyk-fix/src/lib/issues/total-issues-count.ts
  packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pip-requirements/update-dependencies/update-dependencies.spec.ts
  packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
Labels: 🐂 Team Bull

#1918 feat: Pipfile support for `snyk fix`
  packages/snyk-fix/package.json
  packages/snyk-fix/src/lib/errors/command-failed-to-run-error.ts
  packages/snyk-fix/src/lib/errors/custom-error.ts
  packages/snyk-fix/src/plugins/python/get-handler-type.ts
  packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/index.ts
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
  packages/snyk-fix/src/plugins/python/handlers/validate-required-data.ts
  packages/snyk-fix/src/plugins/python/load-handler.ts
  packages/snyk-fix/src/plugins/python/map-entities-per-handler-type.ts
  packages/snyk-fix/src/plugins/python/supported-handler-types.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/update-dependencies.spec.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/workspaces/with-comparator/Pipfile
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/workspaces/with-comparator/Pipfile.lock
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/workspaces/with-dev-deps/Pipfile
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/workspaces/with-dev-deps/Pipfile.lock
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/workspaces/with-django-upgrade/Pipfile
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/workspaces/with-django-upgrade/Pipfile.lock
  packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
  packages/snyk-fix/test/unit/fix.spec.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/pip-requirements/get-handler-type.spec.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/pip-requirements/map-entities-per-handler-type.spec.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/pipenv-pipfile/update-dependencies/update-dependencies.ts
  packages/snyk-fix/tsconfig.json
Labels: 🐂 Team Bull

#1928 feat: release snyk fix Pipfile support
  package.json
Labels: 🐂 Team Bull

#1936 chore: Introduce 'yaml' library to parse YAML IaC files [CC-854]
  package.json
  src/cli/commands/test/iac-local-execution/file-loader.ts
  src/cli/commands/test/iac-local-execution/file-parser.ts
  src/lib/iac/iac-parser.ts
  test/fixtures/iac/depth_detection/one/one.tf
  test/fixtures/iac/depth_detection/root.tf
  test/jest/unit/iac-unit-tests/file-loader.fixtures.ts
  test/jest/unit/iac-unit-tests/file-loader.spec.ts
  test/smoke/spec/iac/snyk_test_local_exec_spec.sh
Labels: :sun_behind_small_cloud: Cloud Config

#1950 Feat/adding cloudformation support [CC-850]
  src/cli/commands/test/iac-local-execution/file-parser.ts
  src/cli/commands/test/iac-local-execution/file-scanner.ts
  src/cli/commands/test/iac-local-execution/local-cache.ts
  src/cli/commands/test/iac-local-execution/parsers/k8s-or-cloudformation-parser.ts
  src/cli/commands/test/iac-local-execution/results-formatter.ts
  src/cli/commands/test/iac-local-execution/types.ts
  src/cli/commands/test/iac-output.ts
  src/lib/iac/constants.ts
  test/fixtures/iac/cloudformation/aurora-valid.yml
  test/fixtures/iac/cloudformation/fargate-valid.json
  test/fixtures/iac/cloudformation/invalid-cfn.yml
  test/fixtures/iac/kubernetes/pod-valid.json
  test/jest/unit/iac-unit-tests/file-parser.cloudformation.fixtures.ts
  test/jest/unit/iac-unit-tests/file-parser.fixtures.ts
  test/jest/unit/iac-unit-tests/file-parser.spec.ts
  test/smoke/spec/iac/snyk_test_local_exec_spec.sh
Labels: :sun_behind_small_cloud: Cloud Config

#1971 fix: Skip empty files on IaC scanning [CC-589]
  src/cli/commands/test/iac-local-execution/file-loader.ts
  test/jest/unit/iac-unit-tests/file-loader.spec.ts
Labels: :sun_behind_small_cloud: Cloud Config
