Repository snyk/cli, pull requests merged in 2021-08, with the labels that each got.

#2120 fix: support of the new Code API
  .github/CODEOWNERS
  package.json
  src/lib/plugins/sast/analysis.ts
  test/fixtures/sast/sample-analyze-folders-response.json
  test/jest/unit/snyk-code/snyk-code-test.spec.ts
Labels: Snyk Code

#2141 feat: if `snyk fix` throws unsupported error, show how to enable
  src/cli/commands/fix/validate-fix-command-is-supported.ts
  test/jest/system/lib/commands/fix/fix.spec.ts
Labels: 🐂 Team Bull

#2145 feat: Enable IaC analytics for ignores
  src/cli/commands/test/iac-local-execution/analytics.ts
Labels: :sun_behind_small_cloud: Cloud Config

#2167 refactor: replace cc parser with split functions [CC-1021]
  package.json
  src/cli/commands/test/iac-local-execution/extract-line-number.ts
  src/cli/commands/test/iac-local-execution/results-formatter.ts
  test/jest/unit/iac-unit-tests/results-formatter.spec.ts
Labels: :sun_behind_small_cloud: Cloud Config
