Repository snyk/cli, pull requests merged in 2021-11, with the labels that each got.

#2348 fix: updated 'code-client' with improved torelance to network issues
  package-lock.json
  package.json
Labels: Snyk Code

#2349 test: cover existing --yarn-workspaces behaviour for exit codes
  test/jest/acceptance/snyk-test/all-projects.spec.ts
  test/jest/acceptance/snyk-test/yarn-workspaces.spec.ts
Labels: 🐂 Team Bull

#2363 Feat: show confidence score
  package-lock.json
  package.json
  src/lib/ecosystems/resolve-test-facts.ts
  src/lib/ecosystems/types.ts
  src/lib/polling/polling-test.ts
  src/lib/snyk-test/legacy.ts
  test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
Labels: Tundra

#2378 fix: unify the retry & contact support errors across commands
  src/lib/common.ts
  src/lib/errors/error-with-retry.ts
  src/lib/errors/index.ts
  src/lib/errors/legacy-errors.js
  src/lib/formatters/format-error-result-summary.ts
  src/lib/monitor/index.ts
  src/lib/plugins/get-multi-plugin-result.ts
  src/lib/protect/patch.js
  src/lib/snyk-test/run-test.ts
  test/jest/acceptance/snyk-test/all-projects.spec.ts
  test/jest/unit/lib/formatters/__snapshots__/format-error-result-summary.spec.ts.snap
Labels: 🐂 Team Bull
