Repository snyk/cli, pull requests merged in 2021-09, with the labels that each got.

#2213 fix: sbt plugin check global plugins
  package-lock.json
  package.json
Labels: Tardis

#2230 refactor: move default upgrade logic into fixAll
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
  packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
Labels: 🐂 Team Bull

#2234 feat(@snyk/fix): catch version resolving failed pip error.
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/update-dependencies.spec.ts
Labels: 🐂 Team Bull

#2231 feat(@snyk/fix): send more detailed error analytics
  packages/snyk-fix/src/index.ts
  src/cli/commands/fix/index.ts
  test/jest/unit/lib/commands/fix/fix.spec.ts
Labels: 🐂 Team Bull

#2235 fix: bubble up SolverProblemError for Poetry
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
  packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/update-dependencies.spec.ts
Labels: 🐂 Team Bull

#2240 refactor: extract re-usable code from poetry fix
  packages/snyk-fix/src/lib/errors/no-fixes-applied.ts
  packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/attempted-changes-summary.ts
  packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
  packages/snyk-fix/src/types.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/update-dependencies.spec.ts
Labels: 🐂 Team Bull

#2245 feat: support analytics from plugins
  src/lib/ecosystems/plugin-analytics.ts
  src/lib/ecosystems/resolve-test-facts.ts
  src/lib/ecosystems/types.ts
  test/jest/unit/lib/ecosystems/fixtures/scan-results.ts
  test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
Labels: Tundra

#2246 feat: track async requests analytics
  src/lib/ecosystems/plugin-analytics.ts
  src/lib/ecosystems/resolve-test-facts.ts
  test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
Labels: Tundra

#2247 feat: replace source cmd with unmanaged
  src/cli/modes.ts
  src/lib/ecosystems/index.ts
  src/lib/plugins/get-extra-project-count.ts
  src/lib/types.ts
  test/jest/system/ecosystems-monitor-cpp.spec.ts
  test/jest/system/lib/commands/fix/fix.spec.ts
  test/jest/unit/all-projects-from-plugins.spec.ts
  test/jest/unit/ecosystems.spec.ts
  test/jest/unit/modes.spec.ts
  test/validate-fix-command-is-supported.spec.ts
Labels: Tundra

#2243 refactor: extract re-usable code from pipenv fix
  packages/snyk-fix/src/plugins/python/handlers/attempted-changes-summary.ts
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
  packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/update-dependencies.spec.ts
Labels: 🐂 Team Bull

#2250 fix: error to handle when no fixes applied
  packages/snyk-fix/src/plugins/python/handlers/ensure-has-updates.ts
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/pipenv-add.ts
  packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
Labels: 🐂 Team Bull

#2253 fix: use new refactored pipenvAdd
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/pipenv-add.ts
Labels: 🐂 Team Bull

#2248 feat: support unmanaged cpp
  package.json
  src/lib/ecosystems/monitor.ts
  src/lib/ecosystems/polling.ts
  src/lib/ecosystems/resolve-monitor-facts.ts
  src/lib/ecosystems/resolve-test-facts.ts
  src/lib/ecosystems/test.ts
  src/lib/polling/common.ts
  src/lib/polling/polling-monitor.ts
  src/lib/polling/polling-test.ts
  src/lib/polling/types.ts
  test/jest/system/ecosystems-monitor-cpp.spec.ts
  test/jest/system/ecosystems-test-cpp.spec.ts
  test/jest/unit/lib/ecosystems/resolve-monitor.facts.spec.ts
  test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
Labels: Tundra

#2254 fix: standardize poetry package names before comparing
  packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
  packages/snyk-fix/test/unit/plugins/python/handlers/poetry/generate-upgrades.spec.ts
Labels: 🐂 Team Bull

#2255 feat: support print-deps cmd
  package.json
  src/lib/ecosystems/resolve-test-facts.ts
  src/lib/ecosystems/types.ts
  src/lib/polling/polling-test.ts
  src/lib/snyk-test/legacy.ts
  src/lib/types.ts
Labels: Tundra

#2260 feat: replace YAML parser with library call [CC-1012]
  package-lock.json
  package.json
  src/cli/commands/test/iac-local-execution/yaml-parser.ts
  src/lib/iac/iac-parser.ts
Labels: :sun_behind_small_cloud: Cloud Config

#2266 feat: test stdout for errors and surface
  packages/snyk-fix/src/index.ts
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/pipenv-add.ts
  packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/poetry-add.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/fails-to-lock/poetry.lock
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/fails-to-lock/pyproject.toml
Labels: 🐂 Team Bull

#2273 Feat/show all attempted fix errors
  packages/snyk-fix/package.json
  packages/snyk-fix/src/lib/output-formatters/format-failed-item.ts
  packages/snyk-fix/src/lib/output-formatters/format-with-changes-item.ts
  packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
  packages/snyk-fix/src/plugins/python/handlers/fail-if-no-updates-applied.ts
  packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
  packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
  packages/snyk-fix/src/plugins/python/index.ts
  packages/snyk-fix/src/plugins/types.ts
  packages/snyk-fix/src/types.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/update-dependencies.spec.ts
  packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/update-dependencies.spec.ts
  packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/show-results-summary.spec.ts.snap
  packages/snyk-fix/test/unit/lib/output-formatters/format-successful-item.spec.ts
  packages/snyk-fix/test/unit/lib/output-formatters/show-results-summary.spec.ts
  src/cli/commands/fix/index.ts
  test/jest/unit/lib/commands/fix/fix.spec.ts
Labels: 🐂 Team Bull

#2277 chore: upgraded @snyk/code-client version
  package-lock.json
  package.json
  src/lib/plugins/sast/analysis.ts
  test/fixtures/sast/sample-analyze-folders-response.json
Labels: Snyk Code
