Repository snyk/cli, pull requests merged in 2022-03, with the labels that each got.

#2787 Add azure blob storage drift source
  help/cli-commands/iac-describe.md
Labels: Documentation

#2788 Add gen-driftignore help
  help/cli-commands/iac-gen-driftignore.md
  test/jest/unit/cli/commands/help/help.spec.ts
Labels: Documentation

#2827 fix: maven root project scan exclude aggregate projects
  package-lock.json
  package.json
  test/tap/cli-monitor.acceptance.test.ts
Labels: Tardis

#3028 feat: Send git contributors to /iac-share-results
  packages/snyk-fix/src/types.ts
  src/lib/ecosystems/types.ts
  src/lib/iac/cli-share-results.ts
  src/lib/iac/envelope-formatters.ts
  test/jest/acceptance/iac/cli-share-results.spec.ts
  test/jest/unit/iac/cli-share-results.fixtures.ts
Labels: :sun_behind_small_cloud: Cloud Config
